# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('title', models.CharField(choices=[('bellhop', 'Bellhop'), ('housekeeping', 'Housekeeping'), ('security', 'Security'), ('frontdesk', 'Front Desk'), ('manager', 'Manager')], max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
