# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currently_employed',
            field=models.BooleanField(default=True),
        ),
    ]
