# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('twin', 'Twin'), ('double', 'Double'), ('queen', 'Queen'), ('deluxe', 'Deluxe Suite'), ('family', 'Family Suite'), ('pent', 'Penthouse')], default='twin', max_length=10)),
                ('room_num', models.CharField(max_length=5)),
                ('floor', models.IntegerField()),
                ('vacancy', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.Hotel')),
            ],
        ),
    ]
