# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_smoking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
