# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'permissions': (('view_hotel', 'Can see the page that lists hotels.'),)},
        ),
    ]
